# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: config.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63onfig.proto\x12\x08reclamos\"\x1c\n\x0eReclamoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x81\x02\n\x0fReclamoResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x19\n\x11\x63omuna_consumidor\x18\x02 \x01(\t\x12\x19\n\x11region_consumidor\x18\x03 \x01(\x05\x12 \n\x18nombre_region_consumidor\x18\x04 \x01(\t\x12\x16\n\x0enombre_mercado\x18\x05 \x01(\t\x12 \n\x18nombre_categoria_mercado\x18\x06 \x01(\t\x12\x11\n\ttipo_prod\x18\x07 \x01(\t\x12\x14\n\x0cmotivo_legal\x18\x08 \x01(\t\x12\x14\n\x0c\x63\x61tegoria_ml\x18\t \x01(\t\x12\x11\n\tresultado\x18\n \x01(\t2X\n\x0fReclamosService\x12\x45\n\x0eGetReclamoById\x12\x18.reclamos.ReclamoRequest\x1a\x19.reclamos.ReclamoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RECLAMOREQUEST']._serialized_start=26
  _globals['_RECLAMOREQUEST']._serialized_end=54
  _globals['_RECLAMORESPONSE']._serialized_start=57
  _globals['_RECLAMORESPONSE']._serialized_end=314
  _globals['_RECLAMOSSERVICE']._serialized_start=316
  _globals['_RECLAMOSSERVICE']._serialized_end=404
# @@protoc_insertion_point(module_scope)
